version: '2.0'
services:
  fetcher-python:
    build: .
    image: "fetcher-python-${STAGE}:1.0"
    container_name: fetcher-python-${STAGE}
    environment:
      DB_ADDRESS: ${DB_ADDRESS}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
